### ISSUE TITLE
hover effects

### ISSUE THREAD

**Issue by mehiarss1991** [WebAhead5/Coronews#23]
in the UX category, from a user perspective i would have preferred it shows me a hover effect or pointer when i hover over the news, so that i know i can click it.
in the UI, i would suggest that the search bar was smaller, on the right, and the weather  bar being smaller on the left, so that they both fit together on the top.
just suggestions but over all i love it, works smoothly, looks good, and does the job.
although in mobile mode it looks pretty good, but some things in the weather bar get cut out.
great job :+1:

**Comment by jrd656** [comment]
That's a great spot. I've added a pointer. In terms of the layout of the search bar and weather, I'm going to leave that as is. Not because I don't think yours is a good idea, but it's going to be a lot of work to remedy. I'll use your idea the next webpage I look at.

We'd forgotten to add the viewport meta tag in. Mobile view should now be improved. :-)
